export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const SAVED_PASSWORD_SUCCESS = 'SAVED_PASSWORD_SUCCESS';
export const SAVED_COMPLETED_SUCCESS = 'SAVED_COMPLETED_SUCCESS';
export const SAVED_USER_SUCCESS = 'SAVED_USER_SUCCESS';
export const SAVED_AUTH_SUCCESS = 'SAVED_AUTH_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOCAL_USER = 'LOCAL_USER';
