export const LOAD_AGENCY_SUCCESS = 'LOAD_AGENCY_SUCCESS';
export const NEW_AGENCY_SUCCESS = 'NEW_AGENCY_SUCCESS';
export const SAVED_AGENCY_SUCCESS = 'SAVED_AGENCY_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

export const classifications = [
  { value: 'C-Corp', label: 'C Corporation' },
  { value: 'Individual', label: 'Individual/Sole Proprietorship/Single Member LLC' },
  { value: 'S-Corp', label: 'S Corporation' },
  { value: 'Partership', label: 'Partnership' },
  { value: 'Trust', label: 'Trust/Estate' },
  { value: 'LLC-C-Corp', label: 'Limited Liability Company (C-Corporation)' },
  { value: 'LLC-S-Corp', label: 'Limited Liability Company (S-Corporation)' },
  { value: 'LLC-Partnership', label: 'Limited Liability Company (Partnership)' },
  { value: 'Other', label: 'Other - Not Listed' },
];

export const carriers = [
  { value: 'Admiral Insurance Company', label: 'Admiral Insurance Company' },
  { value: 'AIG Specialty', label: 'AIG Specialty' },
  { value: 'Allied World', label: 'Allied World' },
  { value: 'American Alternative Insurance Corp', label: 'American Alternative Insurance Corp' },
  { value: 'American Automobile Ins Co', label: 'American Automobile Ins Co' },
  { value: 'Arch', label: 'Arch' },
  { value: 'Berkley Assurance', label: 'Berkley Assurance' },
  { value: 'Capitol Specialty', label: 'Capitol Specialty' },
  { value: 'Certain Underwriters at Lloyd\'s', label: 'Certain Underwriters at Lloyd\'s' },
  { value: 'Endurance American', label: 'Endurance American' },
  { value: 'Everest National', label: 'Everest National' },
  { value: 'General Insurance Co of America', label: 'General Insurance Co of America' },
  { value: 'Great American E&S', label: 'Great American E&S' },
  { value: 'Homeland Ins Company of New York', label: 'Homeland Ins Company of New York' },
  { value: 'Indian Harbor', label: 'Indian Harbor' },
  { value: 'Navigators', label: 'Navigators' },
  { value: 'Scottsdale Indemnity', label: 'Scottsdale Indemnity' },
  { value: 'Utica', label: 'Utica' },
  { value: 'Westport', label: 'Westport' },
  { value: 'XL Specialty', label: 'XL Specialty' },
  { value: 'Other', label: 'Other - Not Listed' },
];

export const states = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  GU: 'Guam',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  PR: 'Puerto Rico',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VI: 'U.S. Virgin Islands',
  VA: 'Virginia',
  WA: 'Washington',
  DC: 'District of Columbia',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};
